### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by Reem-lab** [Bondok6/ToDo-List#8]
## Highlight to say 💯 
 - You make a great job by Refactor functions to pure functions
 - you have clean code no issues 🚀 
 
 <img src="https://media2.giphy.com/media/l1IYfpEF2Tb84asus/giphy.gif"/>

**Comment by gabyse1** [comment]
### Hello @Bondok6 and @andres-condezo 
First, Congratulations on your amazing job!!!

I think it is DRY, and KISS.

**Comment by Bondok6** [comment]
## Hi @gabyse1 , @Reem-lab 🙋‍♂️

Thanks for the feedback ❤
